<?php
// CLI helper to create a .env file for deployment. MUST be run from CLI (SSH).
declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This script must be run from the command line (ssh).\n");
    exit(1);
}

$opts = getopt('', [
    'db-host::', 'db-name::', 'db-user::', 'db-pass::',
    'smtp-host::', 'smtp-port::', 'smtp-user::', 'smtp-pass::',
    'app-email::', 'app-name::', 'app-env::'
]);

function prompt(string $label, bool $hidden = false): string
{
    if ($hidden && function_exists('shell_exec')) {
        // try using stty to disable echo
        echo $label . ': ';
        shell_exec('stty -echo');
        $val = rtrim(fgets(STDIN), "\n");
        shell_exec('stty echo');
        echo "\n";
        return $val;
    }
    echo $label . ': ';
    return rtrim(fgets(STDIN), "\n");
}

$fields = [
    'DB_HOST' => $opts['db-host'] ?? null,
    'DB_NAME' => $opts['db-name'] ?? null,
    'DB_USER' => $opts['db-user'] ?? null,
    'DB_PASS' => $opts['db-pass'] ?? null,
    'SMTP_HOST' => $opts['smtp-host'] ?? null,
    'SMTP_PORT' => $opts['smtp-port'] ?? null,
    'SMTP_USERNAME' => $opts['smtp-user'] ?? null,
    'SMTP_PASSWORD' => $opts['smtp-pass'] ?? null,
    'APP_EMAIL_FROM' => $opts['app-email'] ?? null,
    'APP_EMAIL_NAME' => $opts['app-name'] ?? null,
    'APP_ENV' => $opts['app-env'] ?? 'production',
];

foreach ($fields as $k => $v) {
    if ($v === null) {
        if (in_array($k, ['DB_PASS', 'SMTP_PASSWORD'])) {
            $val = prompt("Enter $k (will not echo)", true);
        } else {
            $val = prompt("Enter $k");
        }
        $fields[$k] = $val;
    }
}

$envPath = __DIR__ . '/../.env';
$content = "# Generated by scripts/create_env.php on " . date('c') . "\n";
foreach ($fields as $k => $v) {
    // escape newlines and double quotes
    $escaped = str_replace('"', '\"', (string) $v);
    $content .= "$k=$escaped\n";
}

if (file_put_contents($envPath, $content) === false) {
    fwrite(STDERR, "Failed to write $envPath. Check permissions.\n");
    exit(2);
}

// Restrict permissions to owner read/write
@chmod($envPath, 0640);

echo "Wrote .env to $envPath\n";
echo "Ensure web server user can read the file and restart services if needed.\n";
exit(0);
