#!/usr/bin/env bash
set -euo pipefail

# install_live.sh
# Interactive installer for the live host. Run via SSH from the app root:
#   cd /path/to/uemlabs
#   sudo bash scripts/install_live.sh

print() { echo -e "\n==> $*"; }

if [ "${BASH_SOURCE[0]}" != "$0" ]; then
  echo "This script should be run, not sourced."; return 1; fi

print "Checking prerequisites..."
command -v php >/dev/null 2>&1 || { echo "php not found in PATH. Please install PHP CLI."; exit 2; }
command -v mysql >/dev/null 2>&1 || echo "Warning: mysql client not found; DB creation may fail unless you use socket auth or run commands manually."

read -rp "Webroot path (default: $(pwd)): " APP_ROOT
APP_ROOT=${APP_ROOT:-$(pwd)}
cd "$APP_ROOT"

echo "\nDatabase setup"
read -rp "DB host (default: localhost): " DB_HOST
DB_HOST=${DB_HOST:-localhost}
read -rp "DB name (default: uemlabs): " DB_NAME
DB_NAME=${DB_NAME:-uemlabs}
read -rp "DB user (default: uem_user): " DB_USER
DB_USER=${DB_USER:-uem_user}
read -rsp "DB password (will not echo): " DB_PASS
echo

echo "\nMySQL root access is required to create the database and user."
read -rp "MySQL root user (default: root): " MYSQL_ROOT_USER
MYSQL_ROOT_USER=${MYSQL_ROOT_USER:-root}
read -rsp "MySQL root password (leave blank to attempt socket auth): " MYSQL_ROOT_PASS
echo

SQL_STATEMENTS="CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\n"
SQL_STATEMENTS+="CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';\n"
SQL_STATEMENTS+="GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';\nFLUSH PRIVILEGES;"

print "Creating database and user..."
if command -v mysql >/dev/null 2>&1; then
  if [ -z "$MYSQL_ROOT_PASS" ]; then
    # Try socket auth (sudo mysql -e) first
    if sudo mysql -e "${SQL_STATEMENTS}" 2>/dev/null; then
      print "DB created using socket auth via sudo mysql"
    else
      print "Socket auth failed; trying mysql client with password prompt"
      echo -e "$SQL_STATEMENTS" | mysql -u"$MYSQL_ROOT_USER" -p
    fi
  else
    echo -e "$SQL_STATEMENTS" | mysql -u"$MYSQL_ROOT_USER" -p"$MYSQL_ROOT_PASS"
  fi
else
  echo "mysql client not found; please run the following SQL as a privileged MySQL user and press Enter when done:";
  echo -e "\n$SQL_STATEMENTS\n";
  read -rp "Press Enter after you have run the SQL statements..." _
fi

print "Creating .env file"
ENV_PATH="$APP_ROOT/.env"
read -rp "SMTP host (default: smtp.hostinger.com): " SMTP_HOST
SMTP_HOST=${SMTP_HOST:-smtp.hostinger.com}
read -rp "SMTP port (default: 465): " SMTP_PORT
SMTP_PORT=${SMTP_PORT:-465}
read -rp "SMTP username (email) (default: info@uemlabs.com): " SMTP_USERNAME
SMTP_USERNAME=${SMTP_USERNAME:-info@uemlabs.com}
read -rsp "SMTP password (will not echo): " SMTP_PASSWORD
echo
read -rp "App email from (default: info@uemlabs.com): " APP_EMAIL_FROM
APP_EMAIL_FROM=${APP_EMAIL_FROM:-info@uemlabs.com}
read -rp "App email name (default: UEM Labs): " APP_EMAIL_NAME
APP_EMAIL_NAME=${APP_EMAIL_NAME:-UEM Labs}
read -rp "APP_ENV (production|development) [default: production]: " APP_ENV
APP_ENV=${APP_ENV:-production}

cat > "$ENV_PATH" <<EOF
# Generated by scripts/install_live.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
DB_HOST=$DB_HOST
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS

SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_USERNAME=$SMTP_USERNAME
SMTP_PASSWORD=$SMTP_PASSWORD
APP_EMAIL_FROM=$APP_EMAIL_FROM
APP_EMAIL_NAME=$APP_EMAIL_NAME

APP_ENV=$APP_ENV
EOF

chmod 640 "$ENV_PATH" || true
print ".env written to $ENV_PATH (permissions set to 640)"

print "Ensure web server user can read the .env file."
read -rp "Web server user (default: www-data): " WWW_USER
WWW_USER=${WWW_USER:-www-data}
chown root:"$WWW_USER" "$ENV_PATH" || echo "chown failed — you may need sudo privileges"

print "Setting up uploads and logs directories"
mkdir -p "$APP_ROOT/uploads" "$APP_ROOT/logs"
chown -R "$WWW_USER":"$WWW_USER" "$APP_ROOT/uploads" "$APP_ROOT/logs" || echo "chown failed — you may need sudo"
chmod -R 750 "$APP_ROOT/uploads" "$APP_ROOT/logs"

print "Attempting to restart web services (apache2/httpd or nginx + php-fpm)"
if command -v systemctl >/dev/null 2>&1; then
  if systemctl list-units --type=service | grep -q apache2; then
    sudo systemctl restart apache2 || echo "Failed to restart apache2"
  elif systemctl list-units --type=service | grep -q httpd; then
    sudo systemctl restart httpd || echo "Failed to restart httpd"
  fi
  if systemctl list-units --type=service | grep -q php; then
    # restart all php-fpm services found
    for svc in $(systemctl list-units --type=service | grep php | awk '{print $1}'); do
      sudo systemctl restart "$svc" || true
    done
  fi
else
  echo "systemctl not available; please restart your webserver/PHP-FPM manually."
fi

print "Running smoke test (if PHP tests exist)"
if [ -f "$APP_ROOT/tests/test_api_full.php" ]; then
  php "$APP_ROOT/tests/test_api_full.php" --verbose || true
else
  echo "No test harness found at tests/test_api_full.php — you can curl endpoints to verify"
fi

print "Installer finished. Quick curl tests to run from your machine:"
echo "curl -sv -X POST https://your-domain.com/api/signup.php -H 'Content-Type: application/json' -d '{\"name\":\"Test\",\"email\":\"test+1@your-domain.com\",\"role\":\"candidate\"}'"
echo "curl -sv -X POST https://your-domain.com/api/login.php -H 'Content-Type: application/json' -d '{\"email\":\"candidate@uemlabs.com\",\"password\":\"candidate123\",\"role\":\"candidate\"}'"

print "If signup still fails with 'Access denied', confirm DB credentials in .env and re-run mysql grants manually."

exit 0
